Partial rollback of I79853ef115ee6c86bc58acc9adedf4c16a6a6964.
The changes to `ecdsa_test.cc` are flaky, as apparently which error code
is received itself is flaky. To be figured out later.

Fixes:

```
C:\b\s\w\ir\cache\builder\boringssl\crypto\fipsmodule\ecdsa\ecdsa_test.cc(103): error: Value of: ErrorsAreAndClear({{ERR_LIB_ECDSA, 100}})
  Actual: false (Got "error:0f000085:elliptic curve routines:OPENSSL_internal:INVALID_SCALAR", wanted "error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE")
Expected: true
Google Test trace:
C:\b\s\w\ir\cache\builder\boringssl\crypto\fipsmodule\ecdsa\ecdsa_test.cc(118): 1
C:\b\s\w\ir\cache\builder\boringssl\crypto\fipsmodule\ecdsa\ecdsa_test.cc(171): secp224k1
```

Bug: 42290241
Change-Id: I511cc480315f84e70944d4bfdd322fb36a6a6964
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/102487
Auto-Submit: Rudolf Polzer <rpolzer@google.com>
Commit-Queue: Adam Langley <agl@google.com>
Presubmit-BoringSSL-Verified: boringssl-scoped@luci-project-accounts.iam.gserviceaccount.com <boringssl-scoped@luci-project-accounts.iam.gserviceaccount.com>
Reviewed-by: Adam Langley <agl@google.com>